adminUser:
  password: vault:vs-pr-277-4arc/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:vs-pr-277-4arc/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:vs-pr-277-4arc/prow:hmacToken
segmentWriteKey: vault:vs-pr-277-4arc:segmentWriteKey
